[package]
name = "wgpu-profiler"
version = "0.21.0"
authors = ["Andreas Reich <r_andreas2@web.de>"]
edition = "2021"
description = "Simple profiler scopes for wgpu using timer queries"
homepage = "https://github.com/Wumpf/wgpu-profiler"
repository = "https://github.com/Wumpf/wgpu-profiler"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[lints]
clippy.doc_markdown = "warn"

[features]
tracy = ["dep:tracy-client", "profiling/profile-with-tracy"]
puffin = ["dep:puffin", "profiling/profile-with-puffin"]

[lib]

[dependencies]
parking_lot = { version = "0.12", default-features = false } # Used for Mutex & RwLock. Note that wgpu already depends on parking_lot as well.
thiserror = { version = "2", default-features = false }
wgpu = { version = "24.0.0", default-features = false }

tracy-client = { version = "0.18", optional = true }
puffin = { version = "0.19.1", optional = true }

[dev-dependencies]
futures-lite = "2"
profiling = "1"
puffin_http = "0.16.1"
tracy-client = "0.18"
wgpu = { version = "24.0.0", default-features = true }
winit = "0.30"
